hardisgroupcom/sfdx-hardis

- .cspell.json
- CHANGELOG.md
- messages/org.json
- src/commands/hardis/org/purge/flow.ts
- src/hooks/init/check-upgrade.ts
use --no-allow-purge-failure to force exit code 1 if flows have not been purged
> Allow purges to fail without making sfdx command fail 

- .cspell.json
- .github/workflows/deploy-ALPHA.yml
- CHANGELOG.md
- messages/org.json
- package.json
- src/commands/hardis/auth/login.ts
- src/commands/hardis/org/test/apex.ts
- src/commands/hardis/project/configure/auth.ts
- src/commands/hardis/project/configure/deployment.ts
- src/commands/hardis/project/deploy/sources/dx.ts
- src/commands/hardis/scratch/create.ts
- src/common/analytics.ts
- src/common/metadata-utils/index.ts
- src/common/utils/index.ts
- src/config/index.ts
- src/hooks/init/check-local-sfdx-hardis-files.ts
- src/hooks/postrun/notify.ts
- src/hooks/postrun/store-cache.ts
- src/hooks/prerun/auth.ts
- Auto-generate **alpha** version of plugin package and associated docker image when publishing from branch **alpha**
- Manage cache storage for CI dependent jobs (cache, artifacts)
- .cache/sfdx-hardis/.sfdx
- .sfdx
- config/user
- Improve org authentication
- New command **hardis:org:test**
- Test org coverage and fail if < 75%
- Installed package management
- Factorize method
- Install packages during hardis:project:deploy:sources:dx
- Allow to reuse scratch org if previous creation failed. Force using --forcenew
- Improve auto-update of local project sfdx-hardis files
- Improve console logs
- Allow to store DevHubSfdxClientId in user sfdx-hardis.yml ( in /user folder)
> Many many things

- .cspell.json
- .jscpd.json
- CHANGELOG.md
- package.json
- src/commands/hardis/org/configure/data.ts
- src/commands/hardis/org/data/export.ts
- src/commands/hardis/org/data/import.ts
- src/commands/hardis/scratch/create.ts
- src/commands/hardis/scratch/delete.ts
- src/commands/hardis/work/new.ts
- src/common/metadata-utils/index.ts
- src/common/utils/dataUtils.ts
- src/common/utils/orgUtils.ts
- src/common/utils/prompts.ts
- yarn.lock
- **hardis:scratch:create**: Initialize data using SFDMU, if defined in .sfdx-hardis.json `dataPackages` property with `importInScratchOrgs: true`
- Example
```yaml
dataPackages:
- dataPath: scripts/data/LightningSchedulerConfig
importInScratchOrgs: true
```
- Propose to update or not default target git branch
- List target git branches if defined in .sfdx-hardis.json `availableTargetBranches` property
- **hardis:scratch:delete**: Propose only scratch orgs related to currently selected Dev Hub
- Display data package label & description, from SFDMU folder config.json properties `sfdxHardisLabel` and `sfdxHardisDescription`
- Display Dev Hub username when listing orgs for selection
> SFDMU + enhancements

- CHANGELOG.md
- README.md
- SECURITY.md
- src/commands/hardis/doc/plugin/generate.ts
- Quick fixes hardis:doc:plugin:generate
- Handle when command.title or command.description is empty
- Add `# Commands` to the README.md truncate markers
> Quick fixes hardis:doc:plugin:generate

- CHANGELOG.md
- src/commands/hardis/org/retrieve/sources/dx.ts
- src/common/metadata-utils/index.ts
- Empty temp directories at the beginning of the command
- Add ForecastingType in the list of ignored metadatas for conversion to sfdx sources
> Fix hardis:org:retrieve:sources:dx

- CHANGELOG.md
- config/sfdx-hardis.jsonschema.json
- src/commands/hardis/scratch/pool/refresh.ts
- src/common/utils/deployTips.ts
New property for scratch org pool config: maxScratchOrgsNumberToCreateOnce (max number of scratch orgs to create during one CI job)
> maxScratchOrgsNumberToCreateOnce

- CHANGELOG.md
- README.md
- config/sfdx-hardis.jsonschema.json
- src/commands/hardis/project/create.ts
- src/commands/hardis/work/new.ts
- src/commands/hardis/work/refresh.ts
- src/commands/hardis/work/resetselection.ts
- src/commands/hardis/work/save.ts
- src/common/utils/deployTipsList.ts
- src/common/utils/gitUtils.ts
- Property `availableTargetBranches` can be defined in `.sfdx-hardis.yml` to list the possible target branches for merge requests
- fix hardis:work:save to propose a git push when the current branch is ahead of origin branch
- New deployTips
- XML item appears more than once
> availableTargetBranches + git push fix for save + deployTips

- Dockerfile
Force sfdx-cli version to 7.173.0 (latest-rc as of 2022-10-17)
> Force sfdx-cli version

- src/commands/hardis/org/purge/apexlog.ts
When i tried it without Tooling API the query didn't remove all logs. Supported by this documentation: https://help.salesforce.com/s/articleView?id=sf.code_debug_log_delete.htm&type=5
> Use tooling API to retrieve ApexLogs

- .gitignore
- src/commands/hardis/project/metadata/findduplicates.ts
- rules for permission sets
- rules for custom labels 
- more rules for profiles
When duplicates are detected, return code will be set to 1, which signifies build systems that they should stop processing job.
Now command returns value, which allows other users to use it in integrations using generated output
```json
{
"status": 1,
"result": [
{
"file": "./force-app/main/default/profiles/Admin.profile-meta.xml",
"key": "Profile.fieldPermissions.field",
"duplicates": [
"Account.AnnualRevenue",
"Account.AnnualRevenue"
]
},
{
"file": "./force-app/main/default/profiles/Admin.profile-meta.xml",
"key": "Profile.classAccesses.apexClass",
"duplicates": [
"FirstClassTest"
]
}
]
}
```
- fixed fake duplicate detection speed report (there was no await)
- simplified string building by using `join`
> add more matchers for duplicate detector

- CHANGELOG.md
- config/sfdx-hardis.jsonschema.json
- src/commands/hardis/work/new.ts
- src/commands/hardis/work/save.ts
- Allow to define property **availableProjects** so when user clicks on New task (hardis:work:new), he/she is asked to select a project, that will be used to build the new git branch name
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/369
> New task & Save enhancements (projects & target branch)

- CHANGELOG.md
- src/commands/hardis/org/retrieve/sources/metadata.ts
- src/commands/hardis/org/test/apex.ts
- src/common/metadata-utils/index.ts
- src/common/utils/deployUtils.ts
- SFDX_RETRIEVE_WAIT_MINUTES
- SFDX_DEPLOY_WAIT_MINUTES
- SFDX_TEST_WAIT_MINUTES
> New ENV variables to override default wait on retrieve/deploy/test commands

- CHANGELOG.md
- defaults/clean/entitlement.json
- src/commands/hardis/project/clean/references.ts
In this pull request,  support for a new cleanup type specific to the **'Entitlement'** object has been added.
Here are the specifics of the changes:
1. A new configuration file has been created **'entitlement.json'** within the **'defaults/clean'** directory. This file will specify the elements to be deleted during the cleanup of the **'Entitlement'** object.
2. A new entry has been added in the reference list in the **'references.ts'** file (line 40 and 109-112) located in the **'src\commands\hardis\project\clean'** path of the repository.
> Added Support for Entitlement Object Cleanup

- CHANGELOG.md
- Dockerfile
- README.md
- defaults/ci/azure-pipelines-checks.yml
- defaults/ci/azure-pipelines-deployment.yml
- defaults/monitoring/azure-pipelines.yml
- docs/deployTips.md
https://github.com/forcedotcom/cli/issues/2445
AllanOricil  is a genius !
> Again a workaround for SF bug

- CHANGELOG.md
- docs/hardis/project/deploy/sources/dx.md
- messages/org.json
- src/commands/hardis/project/deploy/sources/dx.ts
- src/common/utils/classUtils.ts
- src/common/utils/deployUtils.ts
- Added new option `--testlevel RunRepositoryTests` which will dynamically detect all GIT repository test classes and runs the deployment with found tests. This will speed up the validation/deployment on cases where GIT repository module contains subset of all tests found in the org
- Added `--runtests` support in order to pass certain APEX test classes when `--testlevel RunSpecifiedTests` is used
> Enhance deployment command to have support for runtests and dynamic RunRepositoryTests

- src/common/utils/deployUtils.ts
Fixed the issue of passing min coverage string into `updatePullRequestResultCoverage`. Instead pass the float `minCoverage` and `orgCoverage` in order to perform proper comparison of given numbers.
> Fixed PR coverage to use float over string

- CHANGELOG.md
- src/commands/hardis/org/monitor/backup.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/517
Co-authored-by: Yamilet Oliva <38166991+yamioliva@users.noreply.github.com>
> Monitoring: Fix crash when a package name contains a slash

- CHANGELOG.md
- defaults/ci/.gitlab-ci-config.yml
- docs/salesforce-monitoring-config-home.md
- src/commands/hardis/org/diagnose/audittrail.ts
- src/commands/hardis/org/monitor/backup.ts
- src/commands/hardis/project/configure/auth.ts
- src/common/utils/index.ts
- **hardis:org:monitor:backup**: Allow to exclude more metadata types using env variable MONITORING_BACKUP_SKIP_METADATA_TYPES (example: \`MONITORING_BACKUP_SKIP_METADATA_TYPES=CustomLabel,StaticResource,Translation\`)
- When prompt for login, Suggest custom login URL as first choice by default
- CICD: Update default gitlab-ci-config.yml
- Configure Org CI Auth: Do not prevent to use main or master as production branch
> Minor updates about CI , monitoring & config

- Dockerfile
My customer project has few bash scripts which I will use in CI/CD steps. Using official SFDX Hardis image, hence want to have bash support
> Added bash to support project level scripts within Hardis image

- src/commands/hardis/project/deploy/sources/dx.ts
- src/common/ticketProvider/jiraProvider.ts
- src/common/utils/deployUtils.ts
Skip notification providers if there was nothing to deploy (in delta mode)
> Skip post-deployment notifications when empty package.xml, simplify JIRA error logging

- CHANGELOG.md
- defaults/ci/manifest/package-no-overwrite.xml
- docs/salesforce-ci-cd-config-overwrite.md
Remove extra 's' from package-no-overwrite.xml
This incorrectly caused named credentials and remote site settings to be overwritten even though it looked like they were not
> Remove typo from package-no-overwrite.xml

- defaults/monitoring/bitbucket-pipelines.yml
When configuring org monitoring using bitbucket the pipeline step "Run MegaLinter" failed with the following error when running `git pull origin "${BRANCH_NAME}"`
```
+ git pull origin "${BRANCH_NAME}"
From http://bitbucket.org/path/to/repository
* branch            HEAD       -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: …
```
> added a missing line to make pipeline step for megalinter in bitbucket

- .github/linters/.cspell.json
- .github/workflows/build-deploy-docs.yml
- .github/workflows/mega-linter.yml
- CHANGELOG.md
- defaults/ci/.github/workflows/megalinter.yml
- defaults/mkdocs/.github/workflows/build-deploy-docs.yml
- docs/deployTips.md
- docs/grafana/dashboards/DTL - Limits Details.json
- docs/salesforce-monitoring-home.md
- src/commands/hardis/org/diagnose/audittrail.ts
- src/commands/hardis/org/diagnose/licenses.ts
- src/commands/hardis/org/diagnose/unusedusers.ts
- src/commands/hardis/org/monitor/all.ts
- src/commands/hardis/org/purge/flow.ts
- src/common/notifProvider/index.ts
- src/common/utils/apiUtils.ts
- New command **hardis:org:diagnose:licenses** to send used licenses to monitoring logs like Grafana
- **hardis:org:diagnose:audittrail**: Exclude some Add / Remove users from a Territory events from Suspect Audit Trail actions
- **hardis:org:diagnose:unusedusers**: Fix metric name for ActiveUsers
> Monitoring updates + hardis:org:diagnose:licenses

- .github/linters/.cspell.json
- CHANGELOG.md
- config/sfdx-hardis.jsonschema.json
- docs/deployTips.md
- src/commands/hardis/project/deploy/sources/dx.ts
- src/commands/hardis/source/deploy.ts
- src/common/utils/deployTipsList.ts
- src/common/utils/deployUtils.ts
You can define command lines to run before or after a deployment
If the commands are not the same depending on the target org, you can define them into **config/branches/.sfdx-hardis-BRANCHNAME.yml** instead of root **config/.sfdx-hardis.yml**
Example:
```yaml
commandsPreDeploy:
- id: knowledgeUnassign
label: Remove KnowledgeUser right to the user who has it
command: sf data update record --sobject User --where "UserPermissionsKnowledgeUser='true'" --values "UserPermissionsKnowledgeUser='false'" --json
- id: knowledgeAssign
label: Assign Knowledge user to the deployment user
command: sf data update record --sobject User --where "Username='deploy.github@myclient.com'" --values "UserPermissionsKnowledgeUser='true'" --json
commandsPostDeploy:
- id: knowledgeUnassign
label: Remove …
```
> commandsPreDeploy & commandsPostDeploy

- CHANGELOG.md
- docs/salesforce-deployment-assistant-error-list.md
- src/common/gitProvider/gitlab.ts
GITLAB_API_REJECT_UNAUTHORIZED: set to `"false"` if you want to allow connection even without certificate (can be useful on on-premise GitLab instance)
> GITLAB_API_REJECT_UNAUTHORIZED

- CHANGELOG.md
- docs/salesforce-ci-cd-release-home.md
- src/commands/hardis/project/deploy/sources/dx.ts
- src/common/gitProvider/azureDevops.ts
- src/common/gitProvider/bitbucket.ts
- src/common/gitProvider/gitProviderRoot.ts
- src/common/gitProvider/github.ts
- src/common/gitProvider/gitlab.ts
- src/common/gitProvider/index.ts
- src/common/utils/gitUtils.ts
- Allow **hardis:project:deploy:source:dx** notifications to work if the deployment is performed before the Pull Request is merged
- Activate such mode with variable **SFDX_HARDIS_DEPLOY_BEFORE_MERGE**
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/637
> Deployment notifications enhancements

- CHANGELOG.md
- docs/salesforce-deployment-assistant-error-list.md
- src/commands/hardis/org/diagnose/legacyapi.ts
- src/commands/hardis/org/monitor/all.ts
- src/common/utils/deployUtils.ts
- Add message in case of deployment check passing thanks to `testCoverageNotBlocking: true`
- hardis:org:diagnose:legacyapi: fix display error
- Run legacy api detection daily with monitoring, as logs remain only 24h
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/652
> Fix legacy API output message + display deployment message

- .github/linters/.cspell.json
- CHANGELOG.md
- src/common/utils/deployTips.ts
- src/common/utils/deployUtils.ts
- src/common/utils/index.ts
- src/common/utils/xmlUtils.ts
- When git add / stash failure, display a message explaining to run `git config --system core.longpaths true` to solve the issue.
- Improve test classes errors collection during deployment check
- Display the number of elements deployed within a package.xml
> Deployment process polishing

- defaults/utils/sfdxHardisKeyValueStore/objects/SfdxHardisKeyValueStore__c.object
- src/commands/hardis/scratch/create.ts
- src/common/keyValueProviders/salesforce.ts
The following changes were made:
File 1: defaults/utils/sfdxHardisKeyValueStore/objects/SfdxHardisKeyValueStore__c.object
Line 164:
Removed the <gender> tag for the SfdxHardisKeyValueStore object.
Deletion: <gender>Masculine</gender>
Line 167:
Updated <searchLayouts> tag formatting, removing extra space.
Change:
Before: <searchLayouts/>
After: <searchLayouts />
File 2: src/commands/hardis/scratch/create.ts
Line 193:
Fixed comparison operator from === to == in pool alias assignment.
Change:
Before: this.pool === false
After: this.pool == false
Line 260:
Same change as line 193, fixing comparison operator from === to == in another pool check.
Change:
Before: this.pool === false
After: this.pool == false
Line 319:
Updated the --target-org option to --target-dev-hub to better match the …
> Fixing small issues with creating scratch org and scratch org pool

- CHANGELOG.md
- src/common/utils/deployUtils.ts
Adapt stdout checks to output of sf project deploy start
> hardis:project:deploy:smart: Ignore coverage fix

- .prettierrc.js
- .prettierrc.json
- CHANGELOG.md
- src/commands/hardis/project/deploy/smart.ts
- src/common/utils/deployUtils.ts
- src/common/utils/index.ts
- Change default deployment waiting time from 60mn to 120mn
- Display explicit warning message before ConnectedApp deployment so users don't forget to manually create the connected app
Co-authored-by: Matt Farrell <10377148+MattFaz@users.noreply.github.com>
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/822
> Default deployment waiting time 120mn + warning when uploading connected app

- CHANGELOG.md
- src/commands/hardis/scratch/create.ts
Related to https://github.com/cristiand391/oclif-carapace-spec-plugin/issues/1
> Fix doubling -d option in hardis:scratch:create

- CHANGELOG.md
- src/common/metadata-utils/index.ts
In reference to this Issue: https://github.com/hardisgroupcom/sfdx-hardis/issues/902
Compare `.cls` files when tracking git history instead of `.cls-meta.xml`.
I don't see `findMetaFileFromTypeAndName()` used outside of the `unused-apex-classes` command so I think there is limited impact but let me know if I missed something.
> check git history for .cls files instead of .cls-meta.xml

- CHANGELOG.md
- src/commands/hardis/org/data/import.ts
- src/common/utils/dataUtils.ts
- [hardis:org:data:import](https://sfdx-hardis.cloudity.com/hardis/org/data/import/): Allow to run the command in production using, by either:
- Define **sfdmuCanModify** in your .sfdx-hardis.yml config file. (Example: `sfdmuCanModify: prod-instance.my.salesforce.com`)
- Define an environment variable SFDMU_CAN_MODIFY. (Example: `SFDMU_CAN_MODIFY=prod-instance.my.salesforce.com`)
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/921
> Data Import: allow to run in production

- CHANGELOG.md
- src/commands/hardis/org/test/apex.ts
[hardis:org:test:apex](https://sfdx-hardis.cloudity.com/hardis/org/test/apex/): Display the number of failed tests in messages and notifications
> hardis:org:test:apex: Display the number of failed tests in messages and notifications

- CHANGELOG.md
- src/commands/hardis/org/monitor/backup.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/904
> hardis:org:monitor:backup: New option --exclude-namespaces that can be used with --full option

- defaults/monitoring/.gitlab-ci.yml
- src/common/gitProvider/utilsMarkdown.ts
- src/common/utils/deployUtils.ts
- src/common/utils/flowVisualiser/nodeFormatUtils.ts
- src/common/utils/gitUtils.ts
Better handling of errors + Gitlab-ci default config
> More fixes about Flow Git Diff & Doc

- CHANGELOG.md
- src/commands/hardis/org/monitor/backup.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/904
> Backup: New option **--full-apply-filters** that can be used with **--full** option to apply filters anyway

- CHANGELOG.md
- package.json
- src/common/ticketProvider/ticketProviderRoot.ts
> Using target_branch for jira labels when isDeployBeforeMerge flag is true (#924)

- CHANGELOG.md
- src/commands/hardis/org/test/apex.ts
- src/common/utils/deployUtils.ts
- src/common/utils/index.ts
- src/common/utils/wrapUtils.ts
Related to https://github.com/orgs/hardisgroupcom/discussions/983
- Generate a file **hardis-report/apex-coverage-results.json** with Apex code coverage details for the following commands:
- [hardis:project:deploy:smart](https://sfdx-hardis.cloudity.com/hardis/project/deploy/smart/) (only if `COVERAGE_FORMATTER_JSON=true` environment varriable is defined)
- [hardis:org:test:apex](https://sfdx-hardis.cloudity.com/hardis/org/test/apex/) (always)
- [SF Cli deployment wrapper commands](https://sfdx-hardis.cloudity.com/salesforce-deployment-assistant-setup/#using-custom-cicd-pipeline)
Sample content from a deployment command:
```json
[
{
"id": "01p1n00000PPmcpAAD",
"locationsNotCovered": [
{
"column": 0,
"line": 35,
"numExecutions": 0,
"time": -1
},
{
"column": 0,
"line": 36,
"numExecutions": …
```
> Generate a file hardis-report/apex-coverage-results.json with Apex code coverage details

- CHANGELOG.md
- src/commands/hardis/doc/project2markdown.ts
- src/common/gitProvider/utilsMarkdown.ts
- src/common/utils/gitUtils.ts
- src/common/utils/mermaidUtils.ts
- Do not post comments with Flows if there is no real differences
- Truncate the number of flows git diff displayed in Pull Request comments to 30 (override the number using MAX_FLOW_DIFF_TO_SHOW )
- Keep history link in main flow doc if available and history not recalculated
- Remove Flows History mkdocs menu if present from an old sfdx-hardis doc generation
> Fixes about doc gen & flow diff PR comments

- defaults/monitoring/.github/workflows/org-monitoring.yml
I've adjusted the Grafana environment variables in the megalinter part. 
It is now using API_REPORTER instead of NOTIF_API.
> Adjusting the Grafana Configuration Variables in the Megalinter part of org-monitoring.yml

- src/commands/hardis/project/deploy/smart.ts
Fixes an issue where delta deployment after merging a PR isn't calculated correctly.
The issues seems to be the orientation of the delta calculation from "HEAD" to "HEAD^", generating destructive changes if the metadata is new.
inverting the references fixes the issue.
> Thus, the way sfdx-git-delta is used while deploying, it will only generate the delta with the latest commit.
> A temporary workaround would be to activate Squash Commits in the merge request.
> fix: delta after merge is not working as expected

- CHANGELOG.md
- docs/salesforce-monitoring-config-home.md
- src/commands/hardis/org/monitor/backup.ts
- src/common/utils/index.ts
- Full wildcard (`<members>*</members>`)
- Named metadata (`<members>Account.Name</members>`)
- Partial wildcards names (`<members>pi__*</members>` , `<members>*__dlm</members>` , or `<members>prefix*suffix</members>`)
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1154
> Allow wildcards in package-skip-items.xml

- CHANGELOG.md
- src/common/utils/deployUtils.ts
Previously, when generating the org manifest, the members list for metadata types (e.g., ListView, CustomLabel) was sorted upon each individual member addition within the main processing loop. This caused redundant sorting operations, significantly degrading performance—especially in Salesforce orgs with a large number of components. In one recent real-world scenario, this step alone took over 60 minutes to complete.
This commit refactors the logic in buildOrgManifest to:
1. Defer sorting (sortCrossPlatform) until after all elements for a metadata type have been collected, thus performing sorting only once per type.
With these changes, the sorting process now completes in just a few moments, drastically improving the manifest generation speed and efficiency.
> Optimize member sorting during manifest generation

- CHANGELOG.md
- src/commands/hardis/doc/project2markdown.ts
[hardis:doc:project2markdown](https://sfdx-hardis.cloudity.com/hardis/doc/project2markdown/): Define DO_NOT_OVERWRITE_INDEX_MD=true to avoid overwriting the index.md file in docs folder, useful if you want to keep your own index.md file.
> DocGen: new var DO_NOT_OVERWRITE_INDEX_MD

- CHANGELOG.md
- src/commands/hardis/org/monitor/backup.ts
- src/commands/hardis/work/save.ts
- src/common/metadata-utils/index.ts
- src/common/utils/deployUtils.ts
- src/common/utils/filesUtils.ts
- src/common/utils/index.ts
- src/common/utils/projectUtils.ts
- src/common/utils/xmlUtils.ts
- src/config/index.ts
The changes replace the hardcoded API version with a dynamic retrieval using `getApiVersion()` function.
This ensures that the tool uses the API version of the target org, preventing potential compatibility issues.
> Fixes use of org API version

- CHANGELOG.md
- src/common/utils/deployUtils.ts
Addresses an issue with the Salesforce CLI where it incorrectly includes WorkflowFlowAutomation metadata in org-generated package.xml files.
This change filters out the `WorkflowFlowAutomation` metadata type when building the package.xml to avoid errors during deployment.
> Filters WorkflowFlowAutomation from package.xml

- CHANGELOG.md
- src/common/utils/branchStrategyMermaidBuilder.ts
- Refactored logic to ensure preprod branches are only added if they exist, preventing null pointer exceptions.
fixes #1296
> Improve branch and org handling in BranchStrategyMermaidBuilder

- .github/linters/.cspell.json
- CHANGELOG.md
- src/commands/hardis/org/diagnose/audittrail.ts
Extends the audit trail diagnostics by adding new ignored items.
- Updates the list of filtered audit trail events to reduce noise and focus on relevant security events.
- Adds specific events related to external objects, user admin verification, and phone verification to the ignored items list.
> Extends audit trail diagnostics

- src/commands/hardis/org/generate/packagexmlfull.ts
- src/commands/hardis/work/save.ts
Adds a `--no-prompt` flag to the `org:generate:packagexmlfull` command.
This allows users to bypass the interactive org selection prompt and use the default org, particularly useful in CI environments.
Also, updates the documentation URL in `work:save` command and add a WebSocket message to send the documentation URL.
> Adds option to skip org selection prompt

- CHANGELOG.md
- src/commands/hardis/org/diagnose/unsecure-connected-apps.ts
- src/common/utils/index.ts
Improves the retrieval of OAuth tokens for organizations with a large number of tokens. It addresses an issue where Salesforce API limits the number of OAuth tokens returned in a single query.
- Implements a mechanism to recursively query for remaining tokens when the initial query hits the limit of 2500 OAuth Tokens.
- Uses the latest found token's creation date as a constraint for subsequent queries.
- Sorts the OAuth tokens by AppName
> Improves OAuth token retrieval for large orgs

- CHANGELOG.md
- src/commands/hardis/org/files/export.ts
- src/common/utils/filesUtils.ts
- src/common/utils/index.ts
- src/common/utils/limitUtils.ts
Implements the `files:export` command to export file attachments from a Salesforce org based on a predefined configuration.
It introduces a resume/restart capability to handle interrupted exports.
When the `--resume` flag is used (default in CI environments), the command checks existing downloaded files for validity. Valid files are skipped, and invalid files are re-downloaded.
When resume is disabled, the output folder is cleared, and a fresh export starts.
The command also supports interactive project selection and configurable export options.
It handles both ContentVersion and Attachment files, validating file integrity by comparing checksums (ContentVersion) and file sizes (both ContentVersion and Attachment) against Salesforce metadata.
Better handling of API limits
Co-authored-by: …
> Files export: resume + validate downloaded file + better API limits handling
