.cspell.json, CHANGELOG.md, package.json, src/hooks/postrun/notify.ts, yarn.lock
Send MS Teams notifications if set environment variable MS_TEAMS_WEBHOOK_URL or msTeamsWebhookUrl in .sfdx-hardis.yml
=> Teams notifications

CHANGELOG.md, src/commands/hardis/org/purge/flow.ts, src/common/analytics.ts, src/common/utils/index.ts, src/hooks/postrun/notify.ts, src/hooks/prerun/auth.ts
- Fix: Manage Hooks only from hardis namespace commands
=> Manage Hooks only from hardis namespace commands

CHANGELOG.md, src/commands/hardis/org/retrieve/sources/dx.ts, src/common/metadata-utils/index.ts, src/common/utils/index.ts, src/hooks/prerun/auth.ts
- Add more items to metadatas not convertible to sfdx sources
- fix --sandbox argument use
=> Add more items to metadatas not convertible to sfdx sources

CHANGELOG.md, README.md, package.json, src/commands/hardis/project/configure/deployment.ts, src/commands/hardis/project/deploy/sources/dx.ts, src/commands/hardis/scratch/create.ts, src/common/metadata-utils/index.ts, src/config/index.ts, src/hooks/prerun/auth.ts, yarn.lock
- Closes #24 : Change the way of listing installed packages
- Closes #26 : New command sfdx hardis:project:configure:deployments to configure Connected app
- Closes #27: Check in manifest folder for package.xml
=> Less issues now :)

.cspell.json, CHANGELOG.md, README.md, src/commands/hardis/package/install.ts, src/commands/hardis/project/configure/auth.ts, src/commands/hardis/project/deploy/sources/dx.ts, src/commands/hardis/project/deploy/sources/metadata.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, src/common/metadata-utils/index.ts, src/common/utils/index.ts
- Improve package installation 
- Allow to install a package not listed in sfdx-hardis 
- Allow to configure automatic installation during deployments, or not 
- Allow to configure automatic installation during scratch org initialisation, or not
=> Improve package installation

CHANGELOG.md, src/commands/hardis/data/tree/export.ts, src/commands/hardis/org/configure/monitoring.ts, src/commands/hardis/org/select.ts, src/commands/hardis/package/create.ts, src/commands/hardis/package/install.ts, src/commands/hardis/package/version/create.ts, src/commands/hardis/project/configure/auth.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, src/commands/hardis/work/save.ts, src/common/utils/index.ts, src/common/utils/prompts.ts, src/config/index.ts, src/hooks/init/check-local-sfdx-hardis-files.ts
Uniformize user prompts
Unlimited number of elements displayed during interactive git add
=> Prompt enhancements

CHANGELOG.md, README.md, src/hooks/prerun/auth.ts
- Fix org authentication check
=> Fix org authentication check 

.cspell.json, CHANGELOG.md, README.md, src/commands/hardis/package/install.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/scratch/pull.ts, src/commands/hardis/scratch/push.ts, src/common/metadata-utils/index.ts, src/common/utils/deployTips.ts, src/common/utils/deployUtils.ts, src/common/utils/index.ts, src/hooks/prerun/auth.ts
- New command **hardis:source:push**
- New command **hardis:source:pull**
- Various mini-fixes
- Move deploymentPlan.json within .sfdx-hardis.json
- Retry management for execCommand function. ex: `retry: {retryDelay: 30,retryStringConstraint: 'some string present in output', retryMaxAttempts: 5}`
=> push pull commands + deploy process + debugs

CHANGELOG.md, package.json, src/commands/hardis/org/select.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, src/common/utils/index.ts, src/common/utils/prompts.ts, src/common/websocketClient.ts, src/hooks/init/start-ws-client.ts, src/hooks/postrun/notify.ts, src/hooks/prerun/auth.ts, yarn.lock
Closes #65 
- Communicate with VsCode SFDX Hardis extension via WebSocket if server is found
- Send user input prompts to VsCode UI if WebSocket server found
- Send refreshStatus notifications when context is updated
- Arrange some messages for better display on UI
=> WebSockets for VsCode extension UI

CHANGELOG.md, defaults/clean/datadotcom.json, src/common/utils/deployUtils.ts, src/hooks/init/check-local-sfdx-hardis-files.ts
- Fix auto-fix of .gitignore and .forceignore 
- Propose to auto-update .force ignore when there is a pull issue
=> Fix auto-fix + update forceignore when pull fails

CHANGELOG.md, defaults/clean/template.txt, src/commands/hardis/work/save.ts, src/hooks/prerun/check-dependencies.ts
- hardis:work:save : reset ongoing merge if existing 
- Fix git reset call
=> fix hardis:work:save

.cspell.json, CHANGELOG.md, Dockerfile, src/commands/hardis/work/save.ts, src/common/utils/deployTips.ts, src/common/utils/index.ts, src/common/utils/prompts.ts, src/hooks/prerun/auth.ts, src/hooks/prerun/check-dependencies.ts
- Allow to skip pull before save 
- New deployTip: code coverage items with 0% 
- Fix DevHub auth when credential out of date 
- Use latest sfdx-cli package
=> Skip pull before save, fix DevHub auth, use latest sfdx-cli package

CHANGELOG.md, config/pmd-ruleset.xml, src/commands/hardis/project/clean/references.ts, src/commands/hardis/work/save.ts, src/common/utils/index.ts
- hardis:work:save : Fix issue when trying to stage & commit ignored files after project cleaning 
- hardis:project:configure:auth Improve error messge when unable to upload ConnectedApp on production environment
=> save & auth fixes

.cspell.json, CHANGELOG.md, defaults/clean/caseentitlement.json, defaults/clean/localfields.json, src/commands/hardis/project/clean/references.ts, src/commands/hardis/work/refresh.ts
Add Account.NameLocal in localfields clean config
Fix refresh
=> Fix refresh + cleaning

CHANGELOG.md, src/commands/hardis/org/connect.ts
- hardis:org:connect : Propose user to open org in browser if not in CI
=> Connect then open

CHANGELOG.md, config/sfdx-hardis.jsonschema.json, package.json, src/commands/hardis/project/lint.ts, yarn.lock
- New command sfdx hardis:project:lint
- Update .sfdx-hardis.yml configuration JsonSchema
=> hardis:project:lint

.github/workflows/mega-linter.yml, .mega-linter.yml, CHANGELOG.md, config/sfdx-hardis.mega-linter-config.yml, defaults/ci/.gitlab-ci.yml, defaults/mkdocs/mkdocs.yml, defaults/monitoring/.gitlab-ci.yml, defaults/monitoring/.mega-linter.yml, mkdocs.yml, src/commands/hardis/org/configure/monitoring.ts, src/commands/hardis/org/create.ts, src/commands/hardis/project/configure/auth.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, src/common/utils/filesUtils.ts, src/common/utils/index.ts, src/common/utils/orgUtils.ts
- (ALPHA,not really usable yet) Allow to use sandboxes for new task (create from production org, or clone from other sandbox)
- Fixes about scratch org initialization and JWT auth configuration
=> Allow to start a new task with a sandbox

CHANGELOG.md, src/common/utils/deployUtils.ts, src/common/utils/index.ts, src/common/utils/xmlUtils.ts
=> Use same XML indentation than Salesforce (#51)

CHANGELOG.md, src/commands/hardis/project/clean/orgmissingitems.ts, src/commands/hardis/project/deploy/sources/dx.ts, src/common/metadata-utils/index.ts, src/common/utils/deployUtils.ts, src/common/utils/xmlUtils.ts
- Package.xml mixing: fix wildcard `<members>*</members>` management
- List metadatas of target org: complete with what sfpowerkit commands does not return (ListView,CustomLabel)
=> Deployment fixes

CHANGELOG.md, src/commands/hardis/work/save.ts, src/common/utils/deployUtils.ts, src/common/utils/xmlUtils.ts, src/config/index.ts
- Update default apiVersion to 53.0
- Option to not remove empty types when subtracting package.xml
=> Default apiVersion + xml filtering update

CHANGELOG.md, README.md, build.js, config/sfdx-hardis.jsonschema.json, docs/deployTips.md, mkdocs.yml, package.json, src/commands/hardis/mdapi/deploy.ts, src/commands/hardis/org/user/activateinvalid.ts, src/commands/hardis/project/deploy/sources/dx.ts, src/commands/hardis/source/deploy.ts, src/commands/hardis/source/push.ts, src/common/metadata-utils/index.ts, src/common/utils/deployTipsList.ts, src/common/utils/notifUtils.ts, src/common/utils/orgUtils.ts
- Deployment tips online documentation
- hardis:org:user:activateinvalid : new --profiles argument
- Update MsTeams WebHooks ENV variables
- MS_TEAMS_WEBHOOK_URL_CRITICAL
- MS_TEAMS_WEBHOOK_URL_SEVERE
- MS_TEAMS_WEBHOOK_URL_WARNING
- MS_TEAMS_WEBHOOK_URL_INFO
- Allow to install packages during deployment check using INSTALL_PACKAGES_DURING_CHECK_DEPLOY=true env variable
- Enhance prompt org labels
=> Teams hooks + install packages + labels

CHANGELOG.md, src/common/utils/deployTipsList.ts, src/common/utils/xmlUtils.ts
- Fix bug when subtracting a package.xml from another
=> Fix bug when subtracting a package.xml from another

.github/workflows/deploy-ALPHA.yml, .github/workflows/deploy-PROD.yml, .github/workflows/deploy-RELEASE.yml, CHANGELOG.md, README.md
- Fix CI & remove docker image with sfdx-cli@stable as it does not exists anymore
=> Fix CI & remove docker image with sfdx-cli@stable as it does not exists anymore

CHANGELOG.md, README.md, defaults/monitoring/.gitlab-ci.yml, src/commands/hardis/org/configure/monitoring.ts, src/commands/hardis/org/retrieve/packageconfig.ts, src/commands/hardis/org/retrieve/sources/dx.ts, src/commands/hardis/org/retrieve/sources/metadata.ts, src/commands/hardis/project/audit/apiversion.ts, src/commands/hardis/project/audit/callincallout.ts, src/commands/hardis/project/audit/remotesites.ts
Auto-update `.gitlab-ci.yml` if a newest version exists
=> Auto-update `.gitlab-ci.yml` if a newest version exists

CHANGELOG.md, src/commands/hardis/project/configure/auth.ts, src/common/utils/apiUtils.ts, src/common/utils/orgUtils.ts, src/common/utils/poolUtils.ts, src/hooks/prerun/auth.ts
- Fix configure org CI
- Hide auth info from console logs
- Fix Bulk Update job not closed
=> Fixes (config org, hide auth info + bulk update jobs)

.github/workflows/deploy-ALPHA.yml, .github/workflows/deploy-PROD.yml, .github/workflows/deploy-RELEASE.yml, CHANGELOG.md, README.md, src/commands/hardis/misc/toml2csv.ts, src/commands/hardis/project/configure/auth.ts
- toml2csv: Allow `hardcoded` values for concat
- Refactor internal CI to use 7.148.3 as recommended version
=> Fix CI + toml2csv hardcoded prop

README.md, src/common/utils/filesUtils.ts
Compare exported file extension with SF ContentVersion file extension to prevent files with a title containing a dot from having the wrong extension, if any
=> Fix exported file extension (#266)

.github/linters/.checkov.yml, CHANGELOG.md, README.md, config/sfdx-hardis.jsonschema.json, github_conf/branch_protection_rules.json, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, yarn.lock
- Update documentation to initialize scratch org
- Update JSON schema to add `scratchOrgInitApexScripts`
=> Update documentation & JSON schema

.github/workflows/build-deploy-docs.yml, .github/workflows/deploy-ALPHA.yml, .github/workflows/deploy-PROD.yml, .github/workflows/deploy-RELEASE.yml, .github/workflows/test.yml, CHANGELOG.md, defaults/mkdocs/.github/workflows/build-deploy-docs.yml, package.json, src/commands/hardis/misc/toml2csv.ts, src/commands/hardis/org/create.ts, src/commands/hardis/scratch/create.ts, src/common/analytics.ts, src/common/cache/index.ts
- hardis:scratch:create : Avoid error in case of already existing assignment of PermissionSet SfdxHardisDeferSharingRecalc
- Update Node.js minimum version to 16.x
=> Fix scratch creation + ci

CHANGELOG.md, README.md, src/commands/hardis/org/purge/flow.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/297
=> Fix purge flow

.github/workflows/mega-linter.yml, CHANGELOG.md, README.md, docs/salesforce-ci-cd-home.md, package.json, src/commands/hardis/work/new.ts, src/commands/hardis/work/save.ts, src/hooks/prerun/auth.ts
- New task with source tracked sandbox:
- Do not allow to select a major org for dev or config
- Open SF org if selected from the already connected list
- Init packages only if defined in config
- Enhance labels
- Save task: Notify that once the merge request is merged, you must create a new task that will create a new branch
- Improve login error messages
- Use latest version of [MegaLinter](https://megalinter.io)
=> Interactive wizards update + other enhancements

CHANGELOG.md, README.md, docs/deployTips.md, src/commands/hardis/work/new.ts, src/commands/hardis/work/save.ts, src/common/utils/deployTipsList.ts
- Do not add EmailTemplate and Flows as separate items in deploymentPlan, as metadata API now can handle their deployment with the rest of the sources
- Add new deployTip: Missing multi-currency field
- Update label when creating a new task using an existing sandbox
=> DeploymentPlan + deployTips + new task message label

docs/salesforce-ci-cd-create-new-task.md
Initialisation du process de contribution ^^
=> Add Use case section on salesforce-ci-cd-create-new-task.md

CHANGELOG.md, src/common/utils/deployTipsList.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/352
Co-authored-by: przemekrcloudity <95613238+przemekrcloudity@users.noreply.github.com>
=> Add deployTip: Error parsing file

CHANGELOG.md, src/common/metadata-utils/index.ts, src/common/utils/profileUtils.ts
- Change defaut package install mode to **AdminsOnly**
- When minimizing Profiles, do not remove the **personAccountDefault=true** elements
=> Package with AdminsOnly  + keep personAccountDefault on Profile

CHANGELOG.md, README.md, docs/deployTips.md, src/commands/hardis/work/new.ts
- More explicit text to ask user if he/she wants to update its selected sandbox while creating a new task
- Do not ask to change default target branch if there are multiple available branches
=> New task enhancements

CHANGELOG.md, src/common/utils/deployTipsList.ts
Wrong api version
Unknown user
=> New deployTips

CHANGELOG.md, README.md, defaults/ci/azure-pipelines-deployment.yml, docs/deployTips.md, src/common/gitProvider/azureDevops.ts, src/common/gitProvider/gitProviderRoot.ts, src/common/gitProvider/gitlab.ts, src/common/gitProvider/index.ts, src/common/utils/deployUtils.ts
- Improve error message when Git Provider not available
- Update default azure-pipelines-deployment.yml to add mandatory variables for QuickDeploy
=> Improve QuickDeploy for Azure Pipelines

.github/linters/.cspell.json, CHANGELOG.md, README.md, docs/deployTips.md, src/hooks/init/check-upgrade.ts
Co-authored-by: mamasse19 <florian.masson@cloudity.com>
=> Fix upgrade warning message that should not appear when there is no upgrade to perform

CHANGELOG.md, Dockerfile, README.md, defaults/ci/azure-pipelines-checks.yml, defaults/ci/azure-pipelines-deployment.yml, defaults/monitoring/azure-pipelines.yml, docs/deployTips.md
Related bug: https://github.com/forcedotcom/cli/issues/2445
=> Downgrade @salesforce/plugin-deploy-retrieve to v1.17.6 as workaround for SF cli bug 

CHANGELOG.md, README.md, docs/deployTips.md, docs/salesforce-ci-cd-use-install.md
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/417
=> Add info about uninstalling SFDX that has been installed using Windows Installer

src/common/utils/deployUtils.ts
Previous code used string comparison, now new code uses float comparison
=> Fixed code coverage comparison bug

CHANGELOG.md, README.md, docs/deployTips.md, src/hooks/prerun/auth.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/427
Co-authored-by: Fabien Taillon <2465122+FabienTaillon@users.noreply.github.com>
=> Fix auth issue with force:source & force:mdapi wrapper sfdx-hardis commands

CHANGELOG.md, README.md, docs/deployTips.md, docs/index.md, docs/salesforce-ci-cd-home.md, src/common/utils/deployUtils.ts, src/common/utils/wrapUtils.ts, src/hooks/prerun/auth.ts
- Fix return code for wrapper commands force:source:deploy, force:source:push and force:mdapi:deploy
- Fix --skipauth not taken in account with @salesforce/cli
=> Fix return code for wrapped commands + --skipauth not taken in account

CHANGELOG.md, README.md, docs/deployTips.md, src/commands/hardis/org/configure/files.ts, src/commands/hardis/org/files/export.ts, src/common/utils/filesUtils.ts
Co-authored-by: Piotr <503782+piotrekkr@users.noreply.github.com>
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/447
=>  New configuration available to export files: outputFileNameFormat

CHANGELOG.md, README.md, docs/deployTips.md, src/hooks/prerun/auth.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/440
=> Catch "Cannot start the OAuth redirect server on port 1717" and give instructions to user to kill the process

CHANGELOG.md, src/commands/hardis/project/deploy/sources/dx.ts, src/common/utils/deployUtils.ts
Improve delta display in logs
Quick deploy icon in slack notifs
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/468
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/467
=> Delta & notifs adjustments

CHANGELOG.md, docs/salesforce-ci-cd-config-delta-deployment.md, src/commands/hardis/project/deploy/sources/dx.ts, src/common/utils/deployUtils.ts
=> Display FULL / DELTA / Quick Deploy info at the bottom of the logs.

CHANGELOG.md, README.md, docs/deployTips.md, docs/salesforce-ci-cd-config-delta-deployment.md, src/commands/hardis/project/deploy/sources/dx.ts
- If QuickDeploy failed, by default do not use delta for a deployment after a merge between a minor and a major branch
- Allow to tweak delta deployments configuration (but it's really better to use default opiniotated default config !)
=> Delta deployment enhancements

.github/linters/.cspell.json, CHANGELOG.md, src/common/utils/filesUtils.ts
=> fix files export when there is multiple links to same ContentDocument

CHANGELOG.md, package.json, src/commands/hardis/org/monitor/backup.ts, src/common/metadata-utils/index.ts, src/hooks/postrun/notify.ts, yarn.lock
- Generate CSV output for hardis:org:monitor:backup
- Refactor git detection of created/updated/deleted files
=> Generate report for updated files + fix git status

CHANGELOG.md, README.md, docs/deployTips.md, src/commands/hardis/org/monitor/all.ts, src/common/utils/apiUtils.ts
- Handle errors while calling monitoring commands
- Increase jsforce Bulk API Timeout (60 seconds)
=> Handle errors while calling monitoring commands + More bulk timeout

CHANGELOG.md, src/commands/hardis/work/new.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/481
=> hardis:work:new prevent parenthesis in branch name

CHANGELOG.md, src/common/utils/emailUtils.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/562
Co-authored-by: AlainBatesNovuna <140826701+AlainBatesNovuna@users.noreply.github.com>
=> Fix issue when using email notifications with multiple recipients

CHANGELOG.md, config/sfdx-hardis.jsonschema.json, src/commands/hardis/scratch/create.ts
I don't actually work with TS or JS at all so let me know what I have done wrong ;)
=> Add scratch org duration variable

.github/linters/.cspell.json, CHANGELOG.md, README.md, docs/deployTips.md, src/commands/hardis/project/clean/flowpositions.ts, src/commands/hardis/project/clean/references.ts
New command **hardis:project:clean:flowpositions** to replace positions by 0 on AutoLayout Flows, in order to diminish conflicts
Can be automated at each **hardis:work:save** if `flowPositions` added in .sfdx-hardis.yml **autoCleanTypes** property
=> New command to clean flow positions

CHANGELOG.md, docs/salesforce-ci-cd-setup-auth.md
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/597
=> Update authentication documentation

CHANGELOG.md, defaults/ci/Jenkinsfile
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/578
=> Add missing variables in workflows

CHANGELOG.md, docs/salesforce-deployment-assistant-error-list.md, src/commands/hardis/project/deploy/sources/dx.ts, src/commands/hardis/work/save.ts, src/common/utils/deployTips.ts, src/common/utils/deployTipsList.ts, src/common/utils/deployUtils.ts
- hardis:work:save : Update prompt messages
- Remove direct URL to target org in case of deployment failure
- AI Deployment Assistant: Fix identification of error messages
- Add deployment tip "Condition missing reference"
=> Prompt messages + remove direct url + Fix AI Deployment assistant + deployTip

CHANGELOG.md, docs/salesforce-deployment-assistant-error-list.md, src/commands/hardis/org/configure/data.ts, src/commands/hardis/org/configure/files.ts, src/commands/hardis/org/connect.ts, src/commands/hardis/org/create.ts, src/commands/hardis/scratch/create.ts, src/commands/hardis/work/new.ts, src/common/utils/dataUtils.ts, src/common/utils/deployUtils.ts, src/common/utils/filesUtils.ts, src/common/utils/gitUtils.ts, src/common/utils/index.ts, src/common/utils/poolUtils.ts, src/common/utils/prompts.ts, src/hooks/prerun/auth.ts
- Update emojis in prompts to make them more visible
- Replace `sfdx force:org:open` by `sf org open`
- Update default target branch to integration
=> Update emojis & replace force:org:open

.github/linters/.cspell.json, CHANGELOG.md, docs/salesforce-deployment-assistant-error-list.md, src/common/utils/deployTipsList.ts, src/common/utils/deployUtils.ts, src/common/utils/orgConfigUtils.ts, src/common/utils/orgUtils.ts, src/config/index.ts
- Handle bug when a branch .sfdx-hardis.yml config file is empty
- Upgrade default API version to 61
- Additional log when generating manifest package.xml from org
- Add error tip: Network issue (ECONNABORTED, ECONNRESET)
=> Api version + logs + fix empty .sfdx-hardis.yml

.github/workflows/build-deploy-docs.yml, CHANGELOG.md, src/common/utils/deployTips.ts, src/common/utils/deployUtils.ts
- Fix errors collection during deployment check
- Display in deployment check summary when **useSmartDeploymentTests** has been activated
- Do not send coverage formatters options when test level is NoTestRun
=> Deployment check improvements (error collection, output messages)

CHANGELOG.md, src/commands/hardis/org/monitor/backup.ts, src/hooks/init/check-local-sfdx-hardis-files.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/803
=> hardis:org:monitor:backup: Allow spaces in folders

CHANGELOG.md, package.json, src/common/utils/orgConfigUtils.ts, yarn.lock
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/846
=> Fix hardis:org:fix:listviewmine: Use chrome-launcher to find chrome executable to use with puppeteer-core

CHANGELOG.md, src/commands/hardis/org/multi-org-query.ts, src/common/utils/orgUtils.ts
New command hardis:org:multi-org-query allowing to execute a SOQL Bulk Query in multiple orgs and aggregate the results in a single CSV / XLS report
Examples:
```shell
sf hardis:org:multi-org-query
sf hardis:org:multi-org-query --query "SELECT Id,Username FROM User WHERE IsActive = true"
sf hardis:org:multi-org-query --query "SELECT Id,Username FROM User WHERE IsActive = true" --target-orgs nico@cloudity.com nico@cloudity.com.preprod nico@cloudity.com.uat
```
=> Multi-org reports hardis:org:multi-org-query

CHANGELOG.md, src/commands/hardis/org/community/update.ts
@tprouvot you wouldn't have dared to submit your PR without testing the command, right ? 😇
=> QuickFix hardis:org:community:update

CHANGELOG.md, src/commands/hardis/org/user/activateinvalid.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/876
Co-authored-by: paferpotest <82517059+paferpotest@users.noreply.github.com>
=> Fix hardis:org:user:activateinvalid interactive mode

CHANGELOG.md, src/commands/hardis/git/pull-requests/extract.ts, src/common/gitProvider/azureDevops.ts, src/common/gitProvider/gitProviderRoot.ts, src/common/gitProvider/index.ts, src/common/utils/index.ts
=> New command **hardis:git:pull-requests:extract**: Extract Pull Requests from Git Server into CSV/XLS

CHANGELOG.md, src/commands/hardis/scratch/create.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/887
=> Fix bug when scrach org username is > 80 chars

CHANGELOG.md, src/common/utils/authUtils.ts
ask to run again the same command meanwhile we find a way to avoid that using SF CLI architecture
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/889
=> Fix issue with auth just before running a command

CHANGELOG.md, src/commands/hardis/org/monitor/backup.ts
[hardis:org:monitor:backup](https://sfdx-hardis.cloudity.com/hardis/org/monitor/backup/): New mode **--full**, much slower than default filtered one, but that can retrieve ALL metadatas of an org
=> Metadata backup: new option "--full"

CHANGELOG.md, docs/salesforce-ci-cd-setup-existing-org.md, src/commands/hardis/doc/packagexml2markdown.ts, src/commands/hardis/org/retrieve/sources/dx.ts, src/commands/hardis/org/retrieve/sources/metadata.ts, src/common/metadata-utils/index.ts, src/common/utils/xmlUtils.ts
- Fix init sfdx-hardis project commands and docs
- Display warning message in case package.xml has wrong format
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/931
=> Fix init sfdx-hardis project commands and docs + PackageXml format warning

defaults/monitoring/.github/workflows/org-monitoring.yml, defaults/monitoring/azure-pipelines.yml, defaults/monitoring/bitbucket-pipelines.yml, src/commands/hardis/doc/project2markdown.ts, src/commands/hardis/org/monitor/backup.ts, src/common/gitProvider/utilsMarkdown.ts, src/common/utils/flowVisualiser/flowParser.ts, src/common/utils/mermaidUtils.ts
Workflows update documentation
Fix multiple scheduled paths generation
Fix MERMAID_MODE override
=> Flow doc enhancements

.github/linters/.cspell.json, CHANGELOG.md, package.json, src/commands/hardis/org/monitor/backup.ts, src/commands/hardis/project/deploy/notify.ts, src/commands/hardis/project/deploy/smart.ts, src/common/gitProvider/azureDevops.ts, src/common/gitProvider/bitbucket.ts, src/common/gitProvider/gitProviderRoot.ts, src/common/gitProvider/utilsMarkdown.ts, src/common/utils/flowVisualiser/flowParser.ts, src/common/utils/gitUtils.ts, yarn.lock
- New command [hardis:project:deploy:notify](https://sfdx-hardis.cloudity.com/hardis/project/deploy/notify/) to send Pull Request comments (with Flow Visual Git Diff) and Slack / Teams notifications even if you are not using a sfdx-hardis command to check or process a deployment.
- Azure & Bitbucket test & fixes :)
=> hardis:project:deploy:notify

CHANGELOG.md, src/common/utils/flowVisualiser/flowParser.ts
+ Fix parsing of formulas if there is only one
=> Flow doc fix: add description for constants, variables, text template & formulas

CHANGELOG.md, src/commands/hardis/project/generate/flow-git-diff.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1001
=> Flow git diff: New parameters --commit-before and --commit-after

CHANGELOG.md, docs/salesforce-ai-setup.md, src/common/aiProvider/index.ts, src/common/utils/flowVisualiser/flowParser.ts, src/common/utils/mermaidUtils.ts
- Allow to disable calls to AI prompts API using DISABLE_AI=true
- Implement AI cache to save calls to AI prompts API (can be disabled using IGNORE_AI_CACHE)
=> Handle AI cache to save calls + variable DISABLE_AI

CHANGELOG.md, Dockerfile, src/commands/hardis/doc/project2markdown.ts, src/commands/hardis/org/monitor/backup.ts, src/common/aiProvider/utils.ts, src/common/utils/docUtils.ts, src/common/utils/mermaidUtils.ts
- Strip XML to save prompts tokens
- Fix issue when parsing CustomObject metadata
- Install latest version of plugin @salesforce/plugin-deploy-retrieve in Dockerfile to avoid the bug of its current version
=> Doc + AI: Save prompt tokens + fix CustomObject parsing + force install latest @salesforce/plugin-deploy-retrieve

CHANGELOG.md, src/commands/hardis/lint/metadatastatus.ts, src/commands/hardis/lint/missingattributes.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1020
=> Exclude managed items from monitoring warnings

CHANGELOG.md, src/commands/hardis/org/monitor/backup.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1040
=> Backup :Fix issue when there is an empty metadata type

CHANGELOG.md, package.json, src/commands/hardis/doc/project2markdown.ts, src/hooks/auth/auth.ts, yarn.lock
- [hardis:doc:project2markdown](https://sfdx-hardis.cloudity.com/hardis/doc/project2markdown/): Improve Apex docs markdown
- Upgrade apexdocs version
- Fix auth message when selecting default org
=> Improve apex doc

CHANGELOG.md, src/commands/hardis/lint/missingattributes.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1067
=> Do not check for missing descriptions on Data Cloud & Managed package metadatas

CHANGELOG.md, src/commands/hardis/doc/flow2markdown.ts, src/commands/hardis/doc/project2markdown.ts, src/common/utils/mermaidUtils.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1055
=> Doc: display where subflows are used in a new Dependencies paragraph

CHANGELOG.md, src/commands/hardis/org/diagnose/audittrail.ts, src/commands/hardis/org/test/apex.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1084
=> Fix monitoringAllowedSectionsActions

CHANGELOG.md, src/commands/hardis/org/diagnose/unused-connected-apps.ts
Fix crash when a Connected App doesn't have a CreatedBy
=> unused-connected-app fix

CHANGELOG.md, src/common/docBuilder/objectModelBuilder.ts
Co-authored-by: Matheus Delazeri <55641441+matheus-delazeri@users.noreply.github.com>
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1095
=> Build doc: Avoid crash when a lookup field does not contain referenceTo

src/common/utils/filesUtils.ts
Fix 100000 caracter SOQL error limit when exporting more than 5000 contentversion :
- use contentVersionBatchSize =1000 to chunk IN clause .
tests done  : 
- retreive 5600 contentversion (in 1 parentRecord)
- retreive attachment/contentversion
=> Export File : Fix 100000 caracter SOQL error limit

CHANGELOG.md, docs/salesforce-monitoring-inactive-metadata.md, src/commands/hardis/lint/metadatastatus.ts, src/common/gitProvider/utilsMarkdown.ts
Detected incative metadatas
- Approval Processes
- Assignment Rules
- Auto Response Rules
- Escalation Rules
- Forecasting Types
- Record Types
- Workflow Rules
=> hardis:lint:metadatastatus

.github/linters/.cspell.json, package.json, src/commands/hardis/doc/project2markdown.ts, src/common/aiProvider/promptTemplates.ts, src/common/docBuilder/docBuilderLwc.ts, yarn.lock
- LWC doc generation is relying on [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown)
- LWC doc is getting added under the Code section
- Main LWC page is structured like below:
- Preview of LWC documentation using jsdoc-to-markdown:
- Preview of LWC documentation using AI (with Agentforce):
=> Feature: add LWC documentation + LWC AI description

.github/linters/.cspell.json, src/commands/hardis/doc/project2markdown.ts, src/common/aiProvider/promptTemplates.ts, src/common/docBuilder/docBuilderAssignmentRules.ts, src/common/docBuilder/docBuilderAutoResponseRules.ts, src/common/utils/rulesBuilderUtil.ts
Implemented a doc builder for AutoResponse Rules
Added prompt template for AI to describe Autoresponse Rules.
https://github.com/user-attachments/assets/9127c62c-c8a3-4fca-a7f1-6df9c31a230a
=> Feature: introducing AutoResponse Rules documentation + AI description

CHANGELOG.md, defaults/ci/manifest/package-no-overwrite.xml
CI/CD: Add FlowDefinition in default [package-no-overwrite.xml](https://sfdx-hardis.cloudity.com/salesforce-ci-cd-config-overwrite/#package-no-overwritexml), as it is a deprecated metadata
=> Add FlowDefinition in package-no-overwrite.xml

src/common/utils/rulesBuilderUtil.ts
Fixed issue with empty value for the criteria item:
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1205
=> Fix: fixed no value in criteria item

CHANGELOG.md, src/common/aiProvider/index.ts, src/common/utils/markdownUtils.ts
fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1226
=> Fix markdown returned by LLMs so it is compliant with mkdocs

.github/linters/.cspell.json, CHANGELOG.md, src/common/docBuilder/docBuilderPermissionSet.ts, src/common/docBuilder/docBuilderProfile.ts
Fixes https://github.com/hardisgroupcom/sfdx-hardis/issues/1225
cc @mamasse19 :)
=> Authorizations doc: filter non accessible items from tree

CHANGELOG.md, src/commands/hardis/work/new.ts, src/commands/hardis/work/save.ts
Improves the user experience for creating User Stories and managing sandbox environments:
- Updates the work:new command to provide more context when opening sandboxes.
- Sets the selected sandbox org as the default org for subsequent commands.
- Enhances the work:save command to include links to create Merge Requests and display MR documentation.
- Conditionally executes XML cleaning based on configuration, preventing unnecessary processing.
=> Enhances User Story Workflow and Sandbox UX

Dockerfile-ubuntu
=> Ddd ENV SF_DATA_DIR to the Dockerfile to install plugins "globally"

CHANGELOG.md, config/sfdx-hardis.jsonschema.json, docs/salesforce-ci-cd-config-delta-deployment.md, docs/schema/sfdx-hardis-json-schema-parameters.html, src/commands/hardis/work/new.ts
add labels for enums
add links to documentation
enhance descriptions
=> Update json schema doc

CHANGELOG.md, config/sfdx-hardis.jsonschema.json, src/commands/hardis/project/configure/auth.ts, src/commands/hardis/scratch/create.ts, src/common/utils/index.ts
Improves the authentication configuration process for Dev Hubs by:
- Adding a Dev Hub instance URL configuration option.
- Fixing an issue with the auth configuration command for Dev Hubs.
- Updating the scratch org creation description to better reflect its functionality and configuration options.
=> Enhances Dev Hub authentication configuration

.github/linters/.cspell.json, CHANGELOG.md, defaults/ci/.gitlab-ci.yml, defaults/ci/Jenkinsfile, defaults/lintonly/.gitlab-ci.yml, defaults/monitoring/.gitlab-ci.yml, src/commands/hardis/doc/project2markdown.ts, src/commands/hardis/org/monitor/backup.ts, src/common/utils/deployUtils.ts, src/common/utils/index.ts
Improves monitoring configuration and documentation generation with the following changes:
- Adds progress indicators for documentation generation.
- Creates the `force-app/main/default` directory if it doesn't exist before retrieving metadata during backup.
- Displays the connected App XML in logs (while hiding sensitive info) during monitoring configuration.
- Introduces logic to run the first found test class (or allows forcing selection via `SFDX_HARDIS_TECH_DEPLOY_TEST_CLASS`) when configuring monitoring in a production org.
- Adds instructions to use the ghcr.io Docker image to mitigate Docker Hub rate limits in CI/CD configurations.
=> Enhances monitoring configuration and doc gen

Dockerfile-ubuntu
Resolves #1410 
Test result in the local container:
```
$ id
uid=1001(testuser) gid=1001(testuser) groups=1001(testuser)
$ mmdc -i "test.md" -o "test.png" --puppeteerConfigFile "/usr/local/lib/node_modules/sfdx-hardis/defaults/puppeteer-config.json"
Found 1 mermaid charts in Markdown input
✅ ./test-1.png
```
=> Inslall chrome in ubuntu docker image
